version: 0.2

phases:
  build:
    commands:
      - echo "Starting build..."
      - chmod +x hello.sh   #make script to executable :-)
      - chomd +x Namaste.sh
      - ./hello.sh
      - ./Namaste.sh
