AWSTemplateFormatVersion: '2010-09-09'
Description: MLR Lambda Functions Stack 

Parameters:
  UseCaseName:
    Type: String
    Default: mlr


Resources:

  ########################################
  # IAM Role for Lambda Execution
  ########################################
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${UseCaseName}-lambdas-execution-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  ########################################
  # Lambda Functions
  ########################################

  DeltaDetector:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${UseCaseName}-delta-detector'
      Runtime: python3.11
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import json

          def handler(event, context):
              print("Hello from Lambda")

              return {
                  "statusCode": 200,
                  "body": json.dumps({
                      "message": "Hello World",
                      "function": context.function_name
                  })
              }

  SupervisorAgent:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${UseCaseName}-supervisor-agent'
      Runtime: python3.11
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import json

          def handler(event, context):
              print("Hello from Lambda")

              return {
                  "statusCode": 200,
                  "body": json.dumps({
                      "message": "Hello World",
                      "function": context.function_name
                  })
              }

  ReferenceAgent:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${UseCaseName}-reference-agent'
      Runtime: python3.11
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import json

          def handler(event, context):
              print("Hello from Lambda")

              return {
                  "statusCode": 200,
                  "body": json.dumps({
                      "message": "Hello World",
                      "function": context.function_name
                  })
              }

  ContentAnalysisAgent:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${UseCaseName}-content-analysis-agent'
      Runtime: python3.11
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import json

          def handler(event, context):
              print("Hello from Lambda")

              return {
                  "statusCode": 200,
                  "body": json.dumps({
                      "message": "Hello World",
                      "function": context.function_name
                  })
              }

  ComplianceAgent:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${UseCaseName}-compliance-agent'
      Runtime: python3.11
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import json

          def handler(event, context):
              print("Hello from Lambda")

              return {
                  "statusCode": 200,
                  "body": json.dumps({
                      "message": "Hello World",
                      "function": context.function_name
                  })
              }

  QualityAgent:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${UseCaseName}-quality-agent'
      Runtime: python3.11
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import json

          def handler(event, context):
              print("Hello from Lambda")

              return {
                  "statusCode": 200,
                  "body": json.dumps({
                      "message": "Hello World",
                      "function": context.function_name
                  })
              }

  AggregateAgentsResults:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${UseCaseName}-aggregate-agents-results'
      Runtime: python3.11
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import json

          def handler(event, context):
              print("Hello from Lambda")

              return {
                  "statusCode": 200,
                  "body": json.dumps({
                      "message": "Hello World",
                      "function": context.function_name
                  })
              }

  RiskAnalysisAgent:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${UseCaseName}-risk-analysis-agent'
      Runtime: python3.11
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import json

          def handler(event, context):
              print("Hello from Lambda")

              return {
                  "statusCode": 200,
                  "body": json.dumps({
                      "message": "Hello World",
                      "function": context.function_name
                  })
              }

  UploadDocument:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${UseCaseName}-upload-document'
      Runtime: python3.11
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import json

          def handler(event, context):
              print("Hello from Lambda")

              return {
                  "statusCode": 200,
                  "body": json.dumps({
                      "message": "Hello World",
                      "function": context.function_name
                  })
              }

Outputs:
  DeltaDetectorArn:
    Value: !GetAtt DeltaDetector.Arn
  SupervisorAgentArn:
    Value: !GetAtt SupervisorAgent.Arn
  ReferenceAgentArn:
    Value: !GetAtt ReferenceAgent.Arn
  ContentAnalysisAgentArn:
    Value: !GetAtt ContentAnalysisAgent.Arn
  ComplianceAgentArn:
    Value: !GetAtt ComplianceAgent.Arn
  QualityAgentArn:
    Value: !GetAtt QualityAgent.Arn
  AggregateAgentsResultsArn:
    Value: !GetAtt AggregateAgentsResults.Arn
  RiskAnalysisAgentArn:
    Value: !GetAtt RiskAnalysisAgent.Arn
  UploadDocumentArn:
    Value: !GetAtt UploadDocument.Arn
